services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3070:80"
    volumes:
      - .:/app
    working_dir: /app
    command: gunicorn -b 0.0.0.0:80 run:app
    restart: always
