version: '3.8'

services:
  traefik:
    image: traefik:latest
    command:
      - "--api.insecure=true"                       # Dashboard Traefik (apenas dev)
      - "--providers.docker=true"                   # Detecta containers Docker
      - "--entrypoints.web.address=:80"             # Porta HTTP
      - "--entrypoints.websecure.address=:443"      # Porta HTTPS
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true" # SSL automático
      - "--certificatesresolvers.myresolver.acme.email=seu-email@exemplo.com" # Seu email para Let's Encrypt
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"          # Porta HTTP pública
      - "443:443"        # Porta HTTPS pública
      - "8080:8080"      # Dashboard Traefik (opcional)
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "traefik_letsencrypt:/letsencrypt"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Remover exposição direta da porta 3070 para evitar conflito com Traefik
    # ports:
    #   - "3070:80"
    volumes:
      - .:/app
    working_dir: /app
    command: gunicorn -b 0.0.0.0:80 run:app
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.web.rule=Host(`viniciosraymundo.dev`)"     # Substitua pelo seu domínio
      - "traefik.http.routers.web.entrypoints=websecure"
      - "traefik.http.routers.web.tls.certresolver=myresolver"
      - "traefik.http.services.web.loadbalancer.server.port=80"      # Porta interna do container

volumes:
  traefik_letsencrypt:
