version: '3.9'

services:
  web:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "3070:80"
    volumes:
      - .:/app
    working_dir: /app
    command: python run.py
    restart: always
